function phalthrottles(varargin);
% phalthrottles( [...] );
% Throttle Step
h = timeplot({'SV2Step'}, ...
      'Throttle Step', ...
      'Step', ...
      {[0.5 1 0 1.3],'SV2Step'}, ...
      varargin{:} );
