function phalcc(varargin);
% phalcc( [...] );
% Counts C
h = timeplot({'DetC'}, ...
      'Counts C', ...
      'C', ...
      {}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
