function phallp(varargin);
% phallp( [...] );
% Lamps P
h = timeplot({'AModP','BModP','CModP','DModP'}, ...
      'Lamps P', ...
      'P', ...
      {'AModP','BModP','CModP','DModP'}, ...
      varargin{:} );
