function phalrft(varargin);
% phalrft( [...] );
% RF T
h = timeplot({'RFATemp','RFBTemp','RFCTemp','RFDTemp'}, ...
      'RF T', ...
      'T', ...
      {'RFATemp','RFBTemp','RFCTemp','RFDTemp'}, ...
      varargin{:} );
