function phalldt(varargin);
% phalldt( [...] );
% Lamps Det T
h = timeplot({'ADetT','BDetT','CDetT','DDetT'}, ...
      'Lamps Det T', ...
      'DetT', ...
      {'ADetT','BDetT','CDetT','DDetT'}, ...
      varargin{:} );
