function phalfsp(varargin);
% phalfsp( [...] );
% Flows Set Pt
h = timeplot({'NOH1Set','NOH2Set'}, ...
      'Flows Set Pt', ...
      'SetPt', ...
      {'NOH1Set','NOH2Set'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.');
