function phaltsff(varargin);
% phaltsff( [...] );
% Temps SF1F
h = timeplot({'SF1F0','SF1F1','SF1F2','SF1F3','SF1F4','SF1F5','SF1F6'}, ...
      'Temps SF1F', ...
      'SF1F', ...
      {'0','1','2','3','4','5','6'}, ...
      varargin{:} );
