function phalcshc(varargin);
% phalcshc( [...] );
% Ct Stat H Ct
h = ne_dstat({
  'L2Stat', 'HCtStat', 14; ...
	'Ovf16_A', 'HCtStat', 4; ...
	'Ovf16_B', 'HCtStat', 5; ...
	'Ovf16_C', 'HCtStat', 6; ...
	'Ovf16_D', 'HCtStat', 7; ...
	'Ovf20_A', 'HCtStat', 0; ...
	'Ovf20_B', 'HCtStat', 1; ...
	'Ovf20_C', 'HCtStat', 2; ...
	'Ovf20_D', 'HCtStat', 3; ...
	'Resynch', 'HCtStat', 15 }, 'HCt', varargin{:} );
