function phalgdlp(varargin);
% phalgdlp( [...] );
% Gas Deck LP
h = timeplot({'AirLP','N2_LP','N22LP','NO_LP'}, ...
      'Gas Deck LP', ...
      'LP', ...
      {'AirLP','N2\_LP','N22LP','NO\_LP'}, ...
      varargin{:} );
