function phallrffw(varargin);
% phallrffw( [...] );
% Lamps RFFW
h = timeplot({'ARFFW','BRFFW','CRFFW','DRFFW'}, ...
      'Lamps RFFW', ...
      'RFFW', ...
      {'A','B','C','D'}, ...
      varargin{:} );
