function phalthrottlep(varargin);
% phalthrottlep( [...] );
% Throttle Pot
h = timeplot({'SV2Ps'}, ...
      'Throttle Pot', ...
      'Pot', ...
      {[0.5 1 0 1.3], 'SV2Ps'}, ...
      varargin{:} );
