function phalldt(varargin);
% phalldt( [...] );
% Lamps Det T
h = timeplot({'ADetT','BDetT','CDetT','DDetT'}, ...
      'Lamps Det T', ...
      'Det T', ...
      {'A','B','C','D'}, ...
      varargin{:} );
