function phalta(varargin);
% phalta( [...] );
% Temps Air
h = timeplot({'Air1T','Air2T','Air3T'}, ...
      'Temps Air', ...
      'Air', ...
      {'Air1T','Air2T','Air3T'}, ...
      varargin{:} );
