function phalpressurep(varargin);
% phalpressurep( [...] );
% Pressure P
h = timeplot({'SD1_P','SD2_P'}, ...
      'Pressure P', ...
      'P', ...
      {'SD1\_P','SD2\_P'}, ...
      varargin{:} );
