function phalthrottleb(varargin);
% phalthrottleb( [...] );
% Throttle Bits 1
h = ne_dstat({
  'A', 'SV1St', 4; ...
	'B', 'SV1St', 5; ...
	'C', 'SV1St', 7; ...
	'D', 'SV1St', 2; ...
	'I', 'SV1St', 0; ...
	'O', 'SV1St', 1; ...
	'R', 'SV1St', 3; ...
	'Z', 'SV1St', 6 }, 'Bits 1', varargin{:} );
