function phallir(varargin);
% phallir( [...] );
% Lamps IR
h = timeplot({'A_IRV','B_IRV','C_IRV','D_IRV'}, ...
      'Lamps IR', ...
      'IR', ...
      {'A\_IRV','B\_IRV','C\_IRV','D\_IRV'}, ...
      varargin{:} );
