function phallrfbw(varargin);
% phallrfbw( [...] );
% Lamps RFBW
h = timeplot({'ARFBW','BRFBW','CRFBW','DRFBW'}, ...
      'Lamps RFBW', ...
      'RFBW', ...
      {[0.5,1,0,1.3],'A','B','C','D'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
ax = get(h(1),'parent');
set(ax,'ylim',[-0.125 4.5]);