function phalllmt(varargin);
% phalllmt( [...] );
% Lamps LMT
h = timeplot({'A_LMT','B_LMT','C_LMT','D_LMT'}, ...
      'Lamps LMT', ...
      'LMT', ...
      {'A','B','C','D'}, ...
      varargin{:} );
