function phalpumps(varargin);
% phalpumps( [...] );
% Pump Status
% h = timeplot({'PumpS'}, ...
%       'Pump Status', ...
%       'Status', ...
%       {'PumpS'}, ...
%       varargin{:} );
h = ne_dstat({ 'PumpS','PumpS',0},'PumpS', varargin{:});