function phallirs(varargin);
% phallirs( [...] );
% Lamps IR Set
h = timeplot({'A_IRSet','B_IRSet','C_IRSet','D_IRSet'}, ...
      'Lamps IR Set', ...
      'IR Set', ...
      {'A','B','C','D'}, ...
      varargin{:} );
