function phalllmt(varargin);
% phalllmt( [...] );
% Lamps LMT
h = timeplot({'A_LMT','B_LMT','C_LMT','D_LMT'}, ...
      'Lamps LMT', ...
      'LMT', ...
      {'A\_LMT','B\_LMT','C\_LMT','D\_LMT'}, ...
      varargin{:} );
