function phallrfbw(varargin);
% phallrfbw( [...] );
% Lamps RFBW
h = timeplot({'ARFBW','BRFBW','CRFBW','DRFBW'}, ...
      'Lamps RFBW', ...
      'RFBW', ...
      {'A','B','C','D'}, ...
      varargin{:} );
