function phalhkt(varargin);
% phalhkt( [...] );
% HK T
h = timeplot({'PC_1T','PC_2T','VicrT'}, ...
      'HK T', ...
      'T', ...
      {'PC\_1T','PC\_2T','VicrT'}, ...
      varargin{:} );
% Removed Aux_T and PS_2T, 'PS_1T','Cvr1T','Cvr2T','Cvr3T',
