function phalcd(varargin);
% phalcd( [...] );
% Counts D
h = timeplot({'DetD'}, ...
      'Counts D', ...
      'D', ...
      {}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
