function phallirs(varargin);
% phallirs( [...] );
% Lamps IR Set
h = timeplot({'A_IRSet','B_IRSet','C_IRSet','D_IRSet'}, ...
      'Lamps IR Set', ...
      'IRSet', ...
      {'A\_IRSet','B\_IRSet','C\_IRSet','D\_IRSet'}, ...
      varargin{:} );
