function phalhkt(varargin);
% phalhkt( [...] );
% HK T
h = timeplot({'Aux_T','Cvr1T','Cvr2T','Cvr3T','PC_1T','PC_2T','PS_1T','PS_2T','VicrT'}, ...
      'HK T', ...
      'T', ...
      {'Aux\_T','Cvr1T','Cvr2T','Cvr3T','PC\_1T','PC\_2T','PS\_1T','PS\_2T','VicrT'}, ...
      varargin{:} );
