function phalgdf(varargin);
% phalgdf( [...] );
% Gas Deck Flows
h = timeplot({'NOH1Set','NOH1F','NOH2Set','NOH2F'}, ...
      'Gas Deck Flows', ...
      'Flows', ...
      {'NOH1Set','NOH1F','NOH2Set','NOH2F'}, ...
      varargin{:} );
