function phalgdt(varargin);
% phalgdt( [...] );
% Gas Deck T
h = timeplot({'Gas1T','Gas2T','Gas3T','Gas4T','Gas5T'}, ...
      'Gas Deck T', ...
      'T', ...
      {'1','2','3','4','5'}, ...
      varargin{:} );
% Removed Air_T, which was pegged.