function phalbmms(varargin);
% phalbmms( [...] );
% BMM Status
h = ne_dstat({
  'S_LED', 'BMM_cmds', 0; ...
	'F_LED', 'BMM_cmds', 1; ...
	'TRU_cmd', 'BMM_cmds', 2; ...
	'VDD2SENSE', 'BMM_cmds', 3; ...
	'ALRT', 'BMM_cmds', 4 }, 'Status', varargin{:} );
