function phalfsp(varargin);
% phalfsp( [...] );
% Flows Set Pt
h = timeplot({'NOH1Set','NOH2Set'}, ...
      'Flows Set Pt', ...
      'Set Pt', ...
      {'NOH1Set','NOH2Set'}, ...
      varargin{:} );
