function phaldhtrs(varargin);
% phaldhtrs( [...] );
% D Htr Status
h = ne_dstat({
  'DH1_I', 'DS855', 3; ...
	'DH1_S', 'DS855', 1; ...
	'DH2_I', 'DS855', 4; ...
	'DH2_S', 'DS855', 2 }, 'Status', varargin{:} );
