function phallir(varargin);
% phallir( [...] );
% Lamps IR
h = timeplot({'A_IRV','B_IRV','C_IRV','D_IRV'}, ...
      'Lamps IR', ...
      'IR', ...
      {[0.5,1,0,1.3],'A','B','C','D'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
