function phalthrottleb(varargin);
% phalthrottleb( [...] );
% Throttle Bits
h = ne_dstat({
	'C', 'SV2St', 7; ...
	'Z', 'SV2St', 6; ...
	'B', 'SV2St', 5; ...
    'A', 'SV2St', 4; ...
	'R', 'SV2St', 3; ...
	'D', 'SV2St', 2; ...
	'O', 'SV2St', 1; ...
	'I', 'SV2St', 0; ...
	'Scan', 'IXStt', 0 }, 'Bits', varargin{:} );
