function phallrfs(varargin);
% phallrfs( [...] );
% Lamps RF Set
h = timeplot({'RFASet','RFBSet','RFCSet','RFDSet'}, ...
      'Lamps RF Set', ...
      'RFSet', ...
      {[0.5,1,0,1.3],'RFASet','RFBSet','RFCSet','RFDSet'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.');
ax = get(h(1),'parent');
set(ax,'ylim',[-0.125 4.5]);