function phalcb(varargin);
% phalcb( [...] );
% Counts B
h = timeplot({'DetB'}, ...
      'Counts B', ...
      'B', ...
      {}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
