function phalgdhp(varargin);
% phalgdhp( [...] );
% Gas Deck HP
h = timeplot({'AirHP','N2_HP','N22HP','NO_HP'}, ...
      'Gas Deck HP', ...
      'HP', ...
      {'AirHP','N2\_HP','N22HP','NO\_HP'}, ...
      varargin{:} );
