function phalgdf(varargin);
% phalgdf( [...] );
% Gas Deck Flows
h = timeplot({'NOH1F','NOH2F'}, ...
      'Gas Deck Flows', ...
      'Flows', ...
      {'NOH1F','NOH2F'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.','MarkerSize',1);
