function phalthrottlep(varargin);
% phalthrottlep( [...] );
% Throttle Pot
h = timeplot({'SV1Ps','SV2Ps'}, ...
      'Throttle Pot', ...
      'Pot', ...
      {'SV1Ps','SV2Ps'}, ...
      varargin{:} );
